### ISSUE TITLE
[feature request] please add better readme

### ISSUE THREAD

**Issue by henrylatour** [joshdev8/plex-media-server-stack#2]
Please add a more clear readme in terms of env variable usage so I can use this. Also, Thank you for using main instead of master for branch naming convention!

**Comment by henrylatour** [comment]
I look forward to it! Thank you. Right now this feels a little incomplete

**Comment by joshdev8** [comment]
> I look forward to it! Thank you. Right now this feels a little incomplete

😮

**Comment by henrylatour** [comment]
Any idea when you'll have a PR up for this work?

**Comment by joshdev8** [comment]
> Any idea when you'll have a PR up for this work?

Hello @henrylatour I have created a PR, please review when you get a chance and I'll merge it into main. Thank you! 😄
